# Exercise 1 

In this exercise, we will work with the `spam.csv` data file. This file contains text and a label attached to each text. The goal is to clean the text data and then build classifcation models. 

### Exercise 1(a) (2 points)

Load the `pandas` and `numpy` libraries.

In [1]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `spam_df`.

In [2]:
spam_df = pd.read_csv('spam.csv')
spam_df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Exercise 1(c) (2 points)

Report the frequency table of `label`.

In [4]:
round(100*spam_df['label'].value_counts(normalize=True), 2)

label
ham     86.59
spam    13.41
Name: proportion, dtype: float64

### Exercise 1(d) (2 points)

Using the `string` library, remove all the punctuation of the `text` column.

In [5]:
import string
spam_df['text_clean'] = spam_df['text'].str.replace(f"[{string.punctuation}]", "", regex=True)
spam_df.head()

,label,text,text_clean
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...

### Exercise 1(e) (10 points)

Using the `nltk` library, remove stopwords and pronouns from `text_clean` and store in another column called `'text_clean_1'`.

In [6]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
pronouns = ["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves"]

def clean_text(text):

    tokens = word_tokenize(text.lower())

    tokens = [word for word in tokens if word not in stop_words and word not in pronouns]

    tokens = [word.replace('txt', 'text') for word in tokens]

    return " ".join(tokens)

spam_df["text_clean_1"] = spam_df["text_clean"].apply(clean_text)
spam_df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,label,text,text_clean,text_clean_1
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah dont think goes usf lives around though

### Exercise 1(f) (10 points)

Perform Lemmatization of `text_clean_1` and store the results in another column called `text_clean_2` in the `spam_df` data frame.

In [7]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

#Downloading the neccessary NLTK resources
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
# function to get part of the speech for lemmatization
def get_wordnet_pos(word):
    """Map POS tag to first character lemmatize() accepts"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

# function to lemmatize based on its part of speech
def lemmatize_text(text):
    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    lemmatized_tokens = [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]
    return " ".join(lemmatized_tokens)

#apply the lemmatization function to the cleaned text
spam_df["text_clean_2"] = spam_df["text_clean_1"].apply(lemmatize_text)
spam_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,label,text,text_clean,text_clean_1,text_clean_2
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say early hor u c already say,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah dont think goes usf lives around though,nah dont think go usf life around though

### Exercise 1(g) (5 points)

Based on the results from part 1(f), we see digits in some of the text in `text_clean_2`. Remove all the digits from `text_clean_2` and store the results in another column `text_clean_3` in the `spam_df` data frame.

In [8]:
import re

def remove_numbers(text):
    return re.sub(r'\d+', '', text)

spam_df["text_clean_3"] = spam_df["text_clean_2"].apply(remove_numbers)
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry 2 wkly comp win fa cup final tkts 2...,free entry 2 wkly comp win fa cup final tkts 2...,free entry wkly comp win fa cup final tkts st...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,u dun say early hor u c already say,u dun say early hor u c already say,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah dont think goes usf lives around though,nah dont think go usf life around though,nah dont think go usf life around though

### Exercise 1(h) (5 points)

Using the `TfidfVectorizer` function from `sklearn.feature_extraction.text`, convert the `text_clean_3` column into a matrix of TF-IDF features. Use `max_features=30` to create the input features, and map `label` to 0-1.

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_features=38)
X_tfidf = tfidf_vectorizer.fit_transform(spam_df["text_clean_3"]).toarray()
y = spam_df['label'].map({'ham': 0, 'spam': 1})

In [10]:
X_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5572, 38))

### Exercise 1(i) (7 points)

Using 5-fold cross-validation strategy (use `StratifiedKFold`), train and evaluate the out-of-sample performance of the `LogisticRegression` model. Use a probability threshold of 15% (i.e., classify as spam if the predicted probability is greater than or equal to 0.15) and use `recall_score` as measure of performance.

In [12]:
from sklearn.metrics import recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
threshold = 0.15
scores = []

for i, (train_index, test_index) in enumerate(skf.split(X_tfidf, y)):
    X_train, X_test = X_tfidf[train_index], X_tfidf[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model = LogisticRegression(random_state=42)
    model.fit(X_train, y_train)

    y_pred_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_pred_proba >= threshold).astype(int)

    score = recall_score(y_test, y_pred)
    scores.append(score)
    print(f'Fold {i+1} recall score:' , score)

print('Average Recall:', sum(scores) / len(scores))

Fold 1 recall score: 0.8533333333333334
Fold 2 recall score: 0.8866666666666667
Fold 3 recall score: 0.825503355704698
Fold 4 recall score: 0.8187919463087249
Fold 5 recall score: 0.8657718120805369
Average Recall: 0.8500134228187919

### Exercise 1(j) (7 points)

Using the same cross-validation strategy from part 1(i), train and evaluate the out-of-fold performance of the `MultinomialNB` model. Use a probability threshold of 15% (i.e., classify as spam if the predicted probability is greater than or equal to 0.15) and use `recall_score` as measure of performance.

In [13]:
from sklearn.naive_bayes import MultinomialNB

threshold = 0.15
scores = []

for i, (train_index, test_index) in enumerate(skf.split(X_tfidf, y)):
    X_train, X_test = X_tfidf[train_index], X_tfidf[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model = MultinomialNB()
    model.fit(X_train, y_train)

    y_pred_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_pred_proba >= threshold).astype(int)

    score = recall_score(y_test, y_pred)
    scores.append(score)
    print(f'Fold {i+1} recall score:' , score)

print('Average Recall:', sum(scores) / len(scores))

Fold 1 recall score: 0.82
Fold 2 recall score: 0.8733333333333333
Fold 3 recall score: 0.7718120805369127
Fold 4 recall score: 0.7785234899328859
Fold 5 recall score: 0.8389261744966443
Average Recall: 0.8165190156599553

### Exercise 1(k) (8 points)

Using the same cross-validation strategy from part 1(i), train and evaluate the out-of-fold performance of a deep learning model (e.g., using `tensorflow`/`keras` or `pytorch`). Use a probability threshold of 15% (i.e., classify as spam if the predicted probability is greater than or equal to 0.15) and use `recall_score` as measure of performance.

In [14]:
pip install torch

Collecting torch
  Downloading torch-2.14.1-cp311-cp311-win_amd64.whl.metadata (38 kB)
Collecting filelock (from torch)
  Downloading filelock-4.0.9-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in C:\Users\ethan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from torch) (4.12.2)
Collecting setuptools>=77.0.3 (from torch)
  Downloading setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\ethan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from jinja2->torch) (3.0.3)
Downloading torch-2.14.1-cp311-cp311-win_amd64.whl (124.1 MB)
   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
   ---------------------------------------- 0.8/124.1 MB 5.6 MB/s eta 0:00:23
    --------------------------------------- 1.6/124.1 MB 4.4 MB/s eta 0:00:28
    --------------------------------------- 2.4/124.1 MB 4.3 MB/s eta 0:00:29
   - -------------------------------------- 3.1/124.1 MB 4.1 MB/s eta 0:00:30
   - -------------------------------------- 3.7/124.1 MB 4.0 MB/s eta 0:00:31
   - -------------------------------------- 4.2/124.1 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.5/124.1 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 4.7/124.1 MB 3.0 MB/s eta 0:00:40
   - -------------------------------------- 4.7/124.1 MB 3.0 MB/s eta 0:00:40
   - -------------------------------------- 5.0/124.1 MB 2.4 MB/s eta 0:00:51
   - -------------------------------------- 5.0/124.1 MB 2.4 MB/s eta 0:00:51
   - -------------------------------------- 5.2/124.1 MB 2.2 MB/s eta 0:00:56
   - -------------------------------------- 5.5/124.1 MB 2.1 MB/s eta 0:00:58
   - -------------------------------------- 5.8/124.1 MB 1.9 MB/s eta 0:01:01
   - -------------------------------------- 5.8/124.1 MB 1.9 MB/s eta 0:01:01
   - -------------------------------------- 6.0/124.1 MB 1.9 MB/s eta 0:01:04
   - -------------------------------------- 6.0/124.1 MB 1.9 MB/s eta 0:01:04
   -- ------------------------------------- 6.3/124.1 MB 1.7 MB/s eta 0:01:10
   -- ------------------------------------- 6.3/124.1 MB 1.7 MB/s eta 0:01:10
   -- ------------------------------------- 6.6/124.1 MB 1.6 MB/s eta 0:01:13
   -- ------------------------------------- 6.8/124.1 MB 1.6 MB/s eta 0:01:15
   -- ------------------------------------- 6.8/124.1 MB 1.6 MB/s eta 0:01:15
   -- ------------------------------------- 6.8/124.1 MB 1.6 MB/s eta 0:01:15
   -- ------------------------------------- 6.8/124.1 MB 1.6 MB/s eta 0:01:15
   -- ------------------------------------- 6.8/124.1 MB 1.6 MB/s eta 0:01:15
   -- ------------------------------------- 7.1/124.1 MB 1.3 MB/s eta 0:01:31
   -- ------------------------------------- 7.1/124.1 MB 1.3 MB/s eta 0:01:31
   -- ------------------------------------- 7.3/124.1 MB 1.2 MB/s eta 0:01:36
   -- ------------------------------------- 7.3/124.1 MB 1.2 MB/s eta 0:01:36
   -- ------------------------------------- 7.3/124.1 MB 1.2 MB/s eta 0:01:36
   -- ------------------------------------- 7.6/124.1 MB 1.1 MB/s eta 0:01:42
   -- ------------------------------------- 7.6/124.1 MB 1.1 MB/s eta 0:01:42
   -- ------------------------------------- 7.6/124.1 MB 1.1 MB/s eta 0:01:42
   -- ------------------------------------- 7.9/124.1 MB 1.1 MB/s eta 0:01:48
   -- ------------------------------------- 7.9/124.1 MB 1.1 MB/s eta 0:01:48
   -- ------------------------------------- 7.9/124.1 MB 1.1 MB/s eta 0:01:48
   -- ------------------------------------- 8.1/124.1 MB 1.0 MB/s eta 0:01:54
   -- ------------------------------------- 8.1/124.1 MB 1.0 MB/s eta 0:01:54
   -- ------------------------------------- 8.1/124.1 MB 1.0 MB/s eta 0:01:54
   -- ------------------------------------- 8.1/124.1 MB 1.0 MB/s eta 0:01:54
   -- ------------------------------------- 8.1/124.1 MB 1.0 MB/s eta 0:01:54
   -- ------------------------------------- 8.4/124.1 MB 938.8 kB/s eta 0:02:04
   -- ------------------------------------- 8.4/124.1 MB 938.8 kB/s eta 0:02:04
   -- ------------------------------------- 8.4/124.1 MB 938.8 kB/s eta 0:02:04
   -- ------------------------------------- 8.7/124.1 MB 899.3 kB/s eta 0:02:09
   -- ------------------------------------- 8.7/124.1 MB 899.3 kB/s eta 0:02:09
   -- ------------------------------------- 8.9/124.1 MB 895.9 kB/s eta 0:02:09
   -- ------------------------------------- 8.9/124.1 MB 895.9 kB/s eta 0:02:09
   -- ------------------------------------- 9.2/124.1 MB 883.0 kB/s eta 0:02:11
   -- ------------------------------------- 9.2/124.1 MB 883.0 kB/s eta 0:02:11
   -- ------------------------------------- 9.2/124.1 MB 883.0 kB/s eta 0:02:11
   --- ------------------------------------ 9.4/124.1 MB 849.8 kB/s eta 0:02:15
   --- ------------------------------------ 9.4/124.1 MB 849.8 kB/s eta 0:02:15
   --- ------------------------------------ 9.4/124.1 MB 849.8 kB/s eta 0:02:15
   --- ------------------------------------ 9.7/124.1 MB 834.3 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.0/124.1 MB 832.1 kB/s eta 0:02:18
   --- ----------------------------------- 10.2/124.1 MB 770.9 kB/s eta 0:02:28
   --- ----------------------------------- 10.2/124.1 MB 770.9 kB/s eta 0:02:28
   --- ----------------------------------- 10.2/124.1 MB 770.9 kB/s eta 0:02:28
   --- ----------------------------------- 10.5/124.1 MB 754.7 kB/s eta 0:02:31
   --- ----------------------------------- 10.5/124.1 MB 754.7 kB/s eta 0:02:31
   --- ----------------------------------- 10.7/124.1 MB 754.9 kB/s eta 0:02:31
   --- ----------------------------------- 10.7/124.1 MB 754.9 kB/s eta 0:02:31
   --- ----------------------------------- 11.0/124.1 MB 751.0 kB/s eta 0:02:31
   --- ----------------------------------- 11.3/124.1 MB 752.8 kB/s eta 0:02:30
   --- ----------------------------------- 11.3/124.1 MB 752.8 kB/s eta 0:02:30
   --- ----------------------------------- 11.3/124.1 MB 752.8 kB/s eta 0:02:30
   --- ----------------------------------- 11.5/124.1 MB 746.1 kB/s eta 0:02:31
   --- ----------------------------------- 11.5/124.1 MB 746.1 kB/s eta 0:02:31
   --- ----------------------------------- 11.8/124.1 MB 738.2 kB/s eta 0:02:33
   --- ----------------------------------- 11.8/124.1 MB 738.2 kB/s eta 0:02:33
   --- ----------------------------------- 11.8/124.1 MB 738.2 kB/s eta 0:02:33
   --- ----------------------------------- 11.8/124.1 MB 738.2 kB/s eta 0:02:33
   --- ----------------------------------- 12.1/124.1 MB 715.6 kB/s eta 0:02:37
   --- ----------------------------------- 12.1/124.1 MB 715.6 kB/s eta 0:02:37
   --- ----------------------------------- 12.1/124.1 MB 715.6 kB/s eta 0:02:37
   --- ----------------------------------- 12.3/124.1 MB 708.0 kB/s eta 0:02:38
   --- ----------------------------------- 12.3/124.1 MB 708.0 kB/s eta 0:02:38
   --- ----------------------------------- 12.6/124.1 MB 706.6 kB/s eta 0:02:38
   --- ----------------------------------- 12.6/124.1 MB 706.6 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 12.8/124.1 MB 705.2 kB/s eta 0:02:38
   ---- ---------------------------------- 13.1/124.1 MB 656.1 kB/s eta 0:02:50
   ---- ---------------------------------- 13.1/124.1 MB 656.1 kB/s eta 0:02:50
   ---- ---------------------------------- 13.4/124.1 MB 654.3 kB/s eta 0:02:50
   ---- ---------------------------------- 13.4/124.1 MB 654.3 kB/s eta 0:02:50
   ---- ---------------------------------- 13.4/124.1 MB 654.3 kB/s eta 0:02:50
   ---- ---------------------------------- 13.4/124.1 MB 654.3 kB/s eta 0:02:50
   ---- ---------------------------------- 13.4/124.1 MB 654.3 kB/s eta 0:02:50
   ---- ---------------------------------- 13.6/124.1 MB 635.2 kB/s eta 0:02:54
   ---- ---------------------------------- 13.6/124.1 MB 635.2 kB/s eta 0:02:54
   ---- ---------------------------------- 13.9/124.1 MB 630.8 kB/s eta 0:02:55
   ---- ---------------------------------- 13.9/124.1 MB 630.8 kB/s eta 0:02:55
   ---- ---------------------------------- 13.9/124.1 MB 630.8 kB/s eta 0:02:55
   ---- ---------------------------------- 13.9/124.1 MB 630.8 kB/s eta 0:02:55
   ---- ---------------------------------- 13.9/124.1 MB 630.8 kB/s eta 0:02:55
   ---- ---------------------------------- 14.2/124.1 MB 617.1 kB/s eta 0:02:59
   ---- ---------------------------------- 14.4/124.1 MB 621.4 kB/s eta 0:02:57
   ---- ---------------------------------- 14.4/124.1 MB 621.4 kB/s eta 0:02:57
   ---- ---------------------------------- 14.7/124.1 MB 623.0 kB/s eta 0:02:56
   ---- ---------------------------------- 14.9/124.1 MB 626.8 kB/s eta 0:02:55
   ---- ---------------------------------- 15.2/124.1 MB 631.2 kB/s eta 0:02:53
   ---- ---------------------------------- 15.5/124.1 MB 633.9 kB/s eta 0:02:52
   ---- ---------------------------------- 15.5/124.1 MB 633.9 kB/s eta 0:02:52
   ---- ---------------------------------- 15.7/124.1 MB 637.8 kB/s eta 0:02:50
   ----- --------------------------------- 16.0/124.1 MB 641.6 kB/s eta 0:02:49
   ----- --------------------------------- 16.3/124.1 MB 646.1 kB/s eta 0:02:47
   ----- --------------------------------- 16.3/124.1 MB 646.1 kB/s eta 0:02:47
   ----- --------------------------------- 16.5/124.1 MB 647.7 kB/s eta 0:02:47
   ----- --------------------------------- 16.8/124.1 MB 651.6 kB/s eta 0:02:45
   ----- --------------------------------- 17.0/124.1 MB 657.1 kB/s eta 0:02:43
   ----- --------------------------------- 17.3/124.1 MB 661.7 kB/s eta 0:02:42
   ----- --------------------------------- 17.6/124.1 MB 665.4 kB/s eta 0:02:41
   ----- --------------------------------- 17.8/124.1 MB 670.7 kB/s eta 0:02:39
   ----- --------------------------------- 18.1/124.1 MB 675.9 kB/s eta 0:02:37
   ----- --------------------------------- 18.4/124.1 MB 681.0 kB/s eta 0:02:36
   ----- --------------------------------- 18.6/124.1 MB 684.8 kB/s eta 0:02:35
   ----- --------------------------------- 18.6/124.1 MB 684.8 kB/s eta 0:02:35
   ----- --------------------------------- 18.9/124.1 MB 683.0 kB/s eta 0:02:35
   ------ -------------------------------- 19.1/124.1 MB 685.9 kB/s eta 0:02:34
   ------ -------------------------------- 19.4/124.1 MB 689.6 kB/s eta 0:02:32
   ------ -------------------------------- 19.4/124.1 MB 689.6 kB/s eta 0:02:32
   ------ -------------------------------- 19.4/124.1 MB 689.6 kB/s eta 0:02:32
   ------ -------------------------------- 19.7/124.1 MB 687.1 kB/s eta 0:02:33
   ------ -------------------------------- 19.7/124.1 MB 687.1 kB/s eta 0:02:33
   ------ -------------------------------- 19.9/124.1 MB 687.2 kB/s eta 0:02:32
   ------ -------------------------------- 20.2/124.1 MB 687.0 kB/s eta 0:02:32
   ------ -------------------------------- 20.4/124.1 MB 690.5 kB/s eta 0:02:31
   ------ -------------------------------- 20.7/124.1 MB 695.0 kB/s eta 0:02:29
   ------ -------------------------------- 20.7/124.1 MB 695.0 kB/s eta 0:02:29
   ------ -------------------------------- 21.0/124.1 MB 697.9 kB/s eta 0:02:28
   ------ -------------------------------- 21.2/124.1 MB 700.1 kB/s eta 0:02:27
   ------ -------------------------------- 21.5/124.1 MB 665.5 kB/s eta 0:02:35
   ------ -------------------------------- 21.5/124.1 MB 665.5 kB/s eta 0:02:35
   ------ -------------------------------- 21.8/124.1 MB 629.8 kB/s eta 0:02:43
   ------ -------------------------------- 22.0/124.1 MB 620.4 kB/s eta 0:02:45
   ------ -------------------------------- 22.0/124.1 MB 620.4 kB/s eta 0:02:45
   ------- ------------------------------- 22.3/124.1 MB 594.5 kB/s eta 0:02:52
   ------- ------------------------------- 22.3/124.1 MB 594.5 kB/s eta 0:02:52
   ------- ------------------------------- 22.3/124.1 MB 594.5 kB/s eta 0:02:52
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.5/124.1 MB 587.9 kB/s eta 0:02:53
   ------- ------------------------------- 22.8/124.1 MB 556.9 kB/s eta 0:03:02
   ------- ------------------------------- 22.8/124.1 MB 556.9 kB/s eta 0:03:02
   ------- ------------------------------- 22.8/124.1 MB 556.9 kB/s eta 0:03:02
   ------- ------------------------------- 23.1/124.1 MB 554.0 kB/s eta 0:03:03
   ------- ------------------------------- 23.1/124.1 MB 554.0 kB/s eta 0:03:03
   ------- ------------------------------- 23.1/124.1 MB 554.0 kB/s eta 0:03:03
   ------- ------------------------------- 23.3/124.1 MB 558.0 kB/s eta 0:03:01
   ------- ------------------------------- 23.3/124.1 MB 558.0 kB/s eta 0:03:01
   ------- ------------------------------- 23.6/124.1 MB 559.2 kB/s eta 0:03:00
   ------- ------------------------------- 23.6/124.1 MB 559.2 kB/s eta 0:03:00
   ------- ------------------------------- 23.9/124.1 MB 557.8 kB/s eta 0:03:00
   ------- ------------------------------- 23.9/124.1 MB 557.8 kB/s eta 0:03:00
   ------- ------------------------------- 24.1/124.1 MB 560.1 kB/s eta 0:02:59
   ------- ------------------------------- 24.1/124.1 MB 560.1 kB/s eta 0:02:59
   ------- ------------------------------- 24.4/124.1 MB 566.9 kB/s eta 0:02:56
   ------- ------------------------------- 24.6/124.1 MB 568.6 kB/s eta 0:02:55
   ------- ------------------------------- 24.6/124.1 MB 568.6 kB/s eta 0:02:55
   ------- ------------------------------- 24.9/124.1 MB 574.0 kB/s eta 0:02:53
   ------- ------------------------------- 24.9/124.1 MB 574.0 kB/s eta 0:02:53
   ------- ------------------------------- 24.9/124.1 MB 574.0 kB/s eta 0:02:53
   ------- ------------------------------- 25.2/124.1 MB 575.5 kB/s eta 0:02:52
   ------- ------------------------------- 25.4/124.1 MB 577.6 kB/s eta 0:02:51
   -------- ------------------------------ 25.7/124.1 MB 591.8 kB/s eta 0:02:47
   -------- ------------------------------ 25.7/124.1 MB 591.8 kB/s eta 0:02:47
   -------- ------------------------------ 26.0/124.1 MB 593.8 kB/s eta 0:02:46
   -------- ------------------------------ 26.2/124.1 MB 598.2 kB/s eta 0:02:44
   -------- ------------------------------ 26.5/124.1 MB 603.9 kB/s eta 0:02:42
   -------- ------------------------------ 26.7/124.1 MB 614.4 kB/s eta 0:02:39
   -------- ------------------------------ 27.0/124.1 MB 618.1 kB/s eta 0:02:38
   -------- ------------------------------ 27.0/124.1 MB 618.1 kB/s eta 0:02:38
   -------- ------------------------------ 27.3/124.1 MB 617.1 kB/s eta 0:02:37
   -------- ------------------------------ 27.5/124.1 MB 619.4 kB/s eta 0:02:36
   -------- ------------------------------ 27.8/124.1 MB 622.7 kB/s eta 0:02:35
   -------- ------------------------------ 28.0/124.1 MB 632.6 kB/s eta 0:02:32
   -------- ------------------------------ 28.0/124.1 MB 632.6 kB/s eta 0:02:32
   -------- ------------------------------ 28.3/124.1 MB 635.1 kB/s eta 0:02:31
   -------- ------------------------------ 28.3/124.1 MB 635.1 kB/s eta 0:02:31
   -------- ------------------------------ 28.3/124.1 MB 635.1 kB/s eta 0:02:31
   -------- ------------------------------ 28.6/124.1 MB 633.4 kB/s eta 0:02:31
   -------- ------------------------------ 28.6/124.1 MB 633.4 kB/s eta 0:02:31
   --------- ----------------------------- 28.8/124.1 MB 631.4 kB/s eta 0:02:31
   --------- ----------------------------- 29.1/124.1 MB 652.3 kB/s eta 0:02:26
   --------- ----------------------------- 29.1/124.1 MB 652.3 kB/s eta 0:02:26
   --------- ----------------------------- 29.4/124.1 MB 651.8 kB/s eta 0:02:26
   --------- ----------------------------- 29.6/124.1 MB 654.8 kB/s eta 0:02:25
   --------- ----------------------------- 29.6/124.1 MB 654.8 kB/s eta 0:02:25
   --------- ----------------------------- 29.9/124.1 MB 655.4 kB/s eta 0:02:24
   --------- ----------------------------- 29.9/124.1 MB 655.4 kB/s eta 0:02:24
   --------- ----------------------------- 29.9/124.1 MB 655.4 kB/s eta 0:02:24
   --------- ----------------------------- 30.1/124.1 MB 653.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.1/124.1 MB 653.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.4/124.1 MB 655.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.4/124.1 MB 655.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.7/124.1 MB 653.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.7/124.1 MB 653.1 kB/s eta 0:02:24
   --------- ----------------------------- 30.9/124.1 MB 654.5 kB/s eta 0:02:23
   --------- ----------------------------- 31.2/124.1 MB 657.1 kB/s eta 0:02:22
   --------- ----------------------------- 31.2/124.1 MB 657.1 kB/s eta 0:02:22
   --------- ----------------------------- 31.5/124.1 MB 660.9 kB/s eta 0:02:21
   --------- ----------------------------- 31.7/124.1 MB 674.0 kB/s eta 0:02:18
   --------- ----------------------------- 31.7/124.1 MB 674.0 kB/s eta 0:02:18
   --------- ----------------------------- 31.7/124.1 MB 674.0 kB/s eta 0:02:18
   ---------- ---------------------------- 32.0/124.1 MB 669.7 kB/s eta 0:02:18
   ---------- ---------------------------- 32.0/124.1 MB 669.7 kB/s eta 0:02:18
   ---------- ---------------------------- 32.0/124.1 MB 669.7 kB/s eta 0:02:18
   ---------- ---------------------------- 32.0/124.1 MB 669.7 kB/s eta 0:02:18
   ---------- ---------------------------- 32.0/124.1 MB 669.7 kB/s eta 0:02:18
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.2/124.1 MB 655.4 kB/s eta 0:02:21
   ---------- ---------------------------- 32.5/124.1 MB 666.8 kB/s eta 0:02:18
   ---------- ---------------------------- 32.5/124.1 MB 666.8 kB/s eta 0:02:18
   ---------- ---------------------------- 32.8/124.1 MB 665.8 kB/s eta 0:02:18

ERROR: Could not install packages due to an OSError: [WinError 206] The filename or extension is too long: 'C:\\Users\\ethan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\torch-2.14.1.dist-info\\licenses\\third_party\\flash-attention\\third_party\\aiter\\3rdparty\\composable_kernel\\docs'


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: C:\Users\ethan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [19]:
import torch
import torch.nn as nn

torch.manual_seed(42)

class SpamNet(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

threshold = 0.15
scores = []

for i, (train_index, test_index) in enumerate(skf.split(X_tfidf, y)):

    X_train, X_test = X_tfidf[train_index], X_tfidf[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    X_train_t = torch.tensor(X_train, dtype=torch.float32)
    y_train_t = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
    X_test_t = torch.tensor(X_test, dtype=torch.float32)

    model = SpamNet(X_train.shape[1])
    criterion = nn.BCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

    model.train()
    for epoch in range(100):
        optimizer.zero_grad()
        outputs = model(X_train_t)
        loss = criterion(outputs, y_train_t)
        loss.backward()
        optimizer.step()

    model.eval()
    with torch.no_grad():
        y_pred = model(X_test_t).numpy().ravel()
    y_pred_class = (y_pred >= threshold).astype(float)
    score = recall_score(y_test, y_pred_class)
    scores.append(score)
    print(f'Fold {i+1} recall score:' , score)   


print('Average Recall:', sum(scores) / len(scores))

Fold 1 recall score: 0.8333333333333334
Fold 2 recall score: 0.8533333333333334
Fold 3 recall score: 0.8456375838926175
Fold 4 recall score: 0.8120805369127517
Fold 5 recall score: 0.8657718120805369
Average Recall: 0.8420313199105145

### Exercise 1(l) (3 points)

Based on the results from parts 1(i), 1(j) and 1(k), what model would you use to predict spam label?

Based on my results, the 'Logistic Regression' and the  deep slearning model have essentailly the same out of fold recall (approx (8.83)). Because 'Logistic Regression' is simple, I would prefer it.