# Exercise 1 

In this exercise, we will work with the `spam.csv` data file. This file contains text and a label attached to each text. The goal is to clean the text data and then build classifcation models. 

### Exercise 1(a) (2 points)

Load the `pandas` and `numpy` libraries.

In [1]:
import pandas as pd
import numpy as np

### Exercise 1(b) (2 points)

Read the `csv` file and create a data-frame called `spam_df`.

In [2]:
spam_df = pd.read_csv("spam.csv")
spam_df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

### Exercise 1(c) (2 points)

Using the `string` library, remove all the punctuation of the `text` column.

In [3]:
import string 

spam_df["text_clean"] = spam_df["text"].str.replace(f"[{string.punctuation}]", "", regex=True)
spam_df.head()

,label,text,text_clean
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...

### Exercise 1(d) (10 points)

Using the `nltk` library, remove stopwords and pronouns from `text_clean` and store in another column called `'text_clean_1'`.

In [4]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))
pronouns = ['i', 'he', 'she', 'it', 'they', 'we', 'him', 'her', 'his', 'their', 'our', 'u', 'ur', 'im', 'dont', '2', 'ill', '4']

def clean_text(text):

    # Tokenize the text
    tokens = word_tokenize(text.lower())

    # Remove unwanted words
    tokens = [word for word in tokens if word not in stop_words and word not in pronouns]

    # Replacing words
    tokens = [word.replace('txt', 'text') for word in tokens]

    return ' '.join(tokens)

spam_df['text_clean_1'] = spam_df['text_clean'].apply(clean_text)
spam_df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,label,text,text_clean,text_clean_1
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though

### Exercise 1(e) (10 points)

Perform Lemmatization of `text_clean_1` and store the results in another column called `text_clean_2` in the `spam_df` data frame.

In [5]:
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Download necessary NLTK resources
nltk.download('wordnet')
nltk.download("averaged_perceptron_tagger")

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Function to get the part of speech tag for lemmatization
def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"J": wordnet.ADJ,
                "N": wordnet.NOUN,
                "V": wordnet.VERB,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

# Function to lemmatize text
def lemmatize_text(text):
    words = word_tokenize(text)
    lemmatized_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(lemmatized_words)

# Apply the function to lemmatize the text
spam_df['text_clean_2'] = spam_df['text_clean_1'].apply(lemmatize_text)
spam_df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ethan\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

,label,text,text_clean,text_clean_1,text_clean_2
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though

### Exercise 1(f) (5 points)

Based on the results from part 1(f), we see digits in some of the text in `text_clean_2`. Remove all the digits from `text_clean_2` and store the results in another column `text_clean_3` in the `spam_df` data frame.

In [6]:
import re

# Function to remove numbers
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Apply the function to remove numbers from the cleaned text
spam_df['text_clean_3'] = spam_df['text_clean_2'].apply(remove_numbers)
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni,ok lar joking wif oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say,dun say early hor c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though,nah think go usf life around though

### Exercise 1(g) (5 points)

Generate topic features using BERT embeddings on `text_clean_3`.

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns

from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("Loading BERT model...")
bert_model = SentenceTransformer('all-MiniLM-L6-v2')
print("BERT model loaded.")

print("Generating embeddings...")
embeddings = bert_model.encode(spam_df['text_clean_3'].tolist(),
                               show_progress_bar=True,
                               batch_size=32)
print("Embeddings generated.")
print(f'Embeddings shape: {embeddings.shape}')
print(f'Each document is represented by a {embeddings.shape[1]}-dimensional vector.')

C:\Users\ethan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading BERT model...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
C:\Users\ethan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ethan\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
C:\Users\ethan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ethan\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3308.90it/s]

BERT model loaded.
Generating embeddings...

Batches: 100%|██████████| 175/175 [00:13<00:00, 13.19it/s]

Embeddings generated.
Embeddings shape: (5572, 384)
Each document is represented by a 384-dimensional vector.

### Exercise 1(h) (5 points)

Apply the K-Means clustering algorithm to the bert embedding generated in the previous step.

1. Set the number of clusters to k=3.

2. Assign the cluster labels to a new column in `spam_df` called `'kmeans_cluster_label'`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_kmeans_features`.

In [21]:
from sklearn.preprocessing import normalize

embeddings_normalized = normalize(embeddings)

num_clusters = 3
kmeans = KMeans(n_clusters=num_clusters, n_init=20, random_state=42)
kmeans.fit(embeddings_normalized)

spam_df['cluster'] = kmeans.labels_

X_kmeans_features = kmeans.transform(embeddings_normalized)

In [22]:
X_kmeans_features.shape

(5572, 3)

In [23]:
spam_df.head()

,label,text,text_clean,text_clean_1,text_clean_2,text_clean_3,cluster,bert_hierarchical_label
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,go jurong point crazy available bugis n great ...,2,0
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni,ok lar joking wif oni,ok lar joking wif oni,ok lar joking wif oni,2,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts 21s...,free entry wkly comp win fa cup final tkts st ...,1,2
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say,dun say early hor c already say,dun say early hor c already say,dun say early hor c already say,2,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I dont think he goes to usf he lives aroun...,nah think goes usf lives around though,nah think go usf life around though,nah think go usf life around though,0,0

### Exercise 1(i) (5 points)

Hierarchical clustering is a type of density-based grouping used to organize documents based on similarity.

1. Apply Agglomerative Hierarchical Clustering to the L2​-normalized BERT embeddings (bert_embeddings) with k=3 clusters, using the `'ward'` linkage method.

2. Store the resulting cluster assignments in a new column called `'bert_hierarchical_label'` in `spam_df`.

3. Generate new features by computing the distance of each document to the centroid of each of the k=3 clusters. Store these distances in a NumPy array called `X_hierarchical_features`.

In [24]:
from sklearn.cluster import AgglomerativeClustering

num_clusters = 3
agg_clustering = AgglomerativeClustering(n_clusters=num_clusters, linkage="ward")
spam_df['bert_hierarchical_label'] = agg_clustering.fit_predict(embeddings_normalized)
print(spam_df.head())

  label                                               text  \
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

                                          text_clean  \
0  Go until jurong point crazy Available only in ...
1                            Ok lar Joking wif u oni
2  Free entry in 2 a wkly comp to win FA Cup fina...
3        U dun say so early hor U c already then say
4  Nah I dont think he goes to usf he lives aroun...

                                        text_clean_1  \
0  go jurong point crazy available bugis n great ...
1                              ok lar joking wif oni
2  free entry wkly comp win fa cup final tkts 21s...
3                    dun say early hor c already say
4             nah think goes usf lives around though

                                        text_clean_2  \
0  go jurong point crazy available bugis n great ...
1                              ok lar joking wif oni
2  free entry wkly comp win fa cup final tkts 21s...
3                    dun say early hor c already say
4                nah think go usf life around though

                                        text_clean_3  cluster  \
0  go jurong point crazy available bugis n great ...        2
1                              ok lar joking wif oni        2
2  free entry wkly comp win fa cup final tkts st ...        1
3                    dun say early hor c already say        2
4                nah think go usf life around though        0

   bert_hierarchical_label
0                        0
1                        0
2                        2
3                        0
4                        0

In [25]:
from sklearn.metrics.pairwise import euclidean_distances

centroids = []
for i in range (num_clusters):
    centroids.append(embeddings_normalized[spam_df['cluster'] == i].mean(axis=0))
centroids = np.array(centroids)

X_hiearchical_features = euclidean_distances(embeddings_normalized, centroids)

In [26]:
X_hiearchical_features

array([[0.91113836, 0.9414628 , 0.87042344],
       [0.91721344, 1.0041541 , 0.8659455 ],
       [0.93025416, 0.8157456 , 0.8897186 ],
       ...,
       [0.9205432 , 0.99934685, 0.8821379 ],
       [0.9111099 , 0.9275718 , 0.93283457],
       [0.90503174, 1.0180367 , 0.93175656]],
      shape=(5572, 3), dtype=float32)

### Exercise 1(j) (10 points)

Train and evaluate six `LogisticRegression` models as follows:

- Using `kmeans` features as input.
- Using `hierarchical` features as input.
- Using bert embedding features as input.
- Combining `kmeans` + bert embeddings features as input.
- Combining `hierarchical` + bert embeddings features as input.
- Combining `kmeans` + `hierarchical` + bert embeddings features as input.

Evaluate the six models over a five-fold cross validation strategy.

In [27]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

y = spam_df['label'].map({'ham': 0, 'spam': 1})

X_kmeans = X_kmeans_features

X_hiearchical = X_hiearchical_features

X_third = embeddings

X_fourth = np.hstack([X_kmeans, embeddings])

X_Fifth = np.hstack([X_hiearchical, embeddings])

X_Sixth = np.hstack([X_kmeans, X_hiearchical, embeddings])

print("Comparing classificaion proformance of different input combinations")
print("="*60)

model = make_pipeline(StandardScaler(), LogisticRegression(random_state=42))

feature_sets = {
    "First Input": X_kmeans,
    "Second Input": X_hiearchical,
    "Third Input": X_third,
    "Fourth Input": X_fourth,
    "Fifth Input": X_Fifth,
    "Sixth Input": X_Sixth
}

results = {}
for name, X in feature_sets.items():
    scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42))
    results[name] = (scores.mean(), scores.std())
    print(f"{name}: Mean Accuracy = {scores.mean():.4f}, Std = {scores.std():.4f}")

best_feature_set = max(results, key=lambda k: results[k][0])
print(f"\nBest feature set: {best_feature_set} with Mean Accuracy = {results[best_feature_set][0]:.4f}, Std = {results[best_feature_set][1]:.4f}")

Comparing classificaion proformance of different input combinations
============================================================
First Input: Mean Accuracy = 0.9282, Std = 0.0053
Second Input: Mean Accuracy = 0.9282, Std = 0.0053
Third Input: Mean Accuracy = 0.9725, Std = 0.0044
Fourth Input: Mean Accuracy = 0.9725, Std = 0.0044
Fifth Input: Mean Accuracy = 0.9725, Std = 0.0044
Sixth Input: Mean Accuracy = 0.9724, Std = 0.0044

Best feature set: Third Input with Mean Accuracy = 0.9725, Std = 0.0044